/*
Controller is used for setting and removing the controls during different game states
*/

var Controller;

Controller = (function() {

  function Controller(root, name) {
    this.root = root;
    this.name = name;
    console.log("");
  }

  return Controller;

})();

// Generated by CoffeeScript 1.5.0-pre
