var Engine;

Engine = function() {
  this.canvas = window.canvas;
  this.stage = new createjs.Stage(window.canvas);
  this.backdrop = function() {
    var background, canvas, fullRectangle, stage;
    stage = this.stage;
    canvas = this.canvas;
    fullRectangle = new createjs.Graphics().beginFill("#000").drawRect(0, 0, canvas.width, canvas.height);
    background = new createjs.Shape(fullRectangle);
    stage.addChild(background);
    return stage.update();
  };
  return console.log("Engine started. Vrroom.");
};

// Generated by CoffeeScript 1.5.0-pre
